thenicekat/handoutsforyou

.github/pull_request_template.md

feat: create pull_request_template.md

---

scripts/docx_to_pdf.py

Changed the script to make it more reusable in the future. Extracted repeating portions into a reusable function.

refactor: updated docx_to_pdf.py

---

.github/pull_request_template.md

Changed this PR template.
Please delete options that are not relevant.

feat: updated pull_request_template.md

---

pages/api/summary/data.ts

Fixed the occurrence of the new table name

fix: fixed table name

---

pages/rants/index.tsx

<pre>
Reversed order of rants.
</pre>

fix: reversed rants order

---

.gitignore
pages/courses/resources/index.tsx
pages/courses/reviews/index.tsx
pnpm-lock.yaml

<pre>
Minor change to the UI: FAB in the course review/resources page
For smaller screens, the 'Add resource'/'Add review' button is replaced with a floating action button
</pre>

feat: FAB for add resource/review

---

pages/api/ps/cutoffs/ps2.ts
pages/ps/index.tsx
pages/ps/ps2/index.tsx
types/PSData.tsx

<pre>
Include summary of change here.
We had a lot of data for ps 2 but most of it was not shown.
A brief description of the your implementation method can be helpful too. If the implemented method/algorithm is not so
well-known, it would be helpful to add a link to an article explaining it with more details.
</pre>

feat: change table format for ps 2 data

---

components/HandoutsPerYear.tsx
components/Menu.tsx
pages/api/ps/cutoffs/ps2.ts
pages/courses/resources/index.tsx
pages/courses/reviews/index.tsx
pages/handouts/index.tsx
pages/placements/ctcs/index.tsx
pages/placements/index.tsx
pages/ps/index.tsx
pages/ps/ps1/index.tsx
pages/ps/ps2/index.tsx
pages/rants/index.tsx
pages/si/companies.tsx

<pre>
Added unsorted mode icon to Placement data table, changed icon style
Replicate the sorting in the PS 2 table
</pre>

Sorting styling fix + PS 2 Sorting

---

pages/api/courses/grading/add.ts
pages/api/courses/grading/get.ts
pages/courses/grading/add.tsx
pages/courses/grading/index.tsx
types/CourseGrading.tsx

<pre>
This PR introduces a slight change to the course grading page allowing for different branches' grading to be uploaded for common courses (such as Phoenix courses).
Course grades are now associates with individual branches based on the course codes, or a generic ALL if only one department is associated with a course/all branches have grouped grading.
Would require a non-nullable field called 'dept' (text), part of the key in course_grading, with a default values of 'ALL' (for all courses uploaded so far as well)
</pre>

Grading course split

---

components/Menu.tsx

<pre>
Include summary of change here.
A brief description of the your implementation method can be helpful too. If the implemented method/algorithm is not so
well-known, it would be helpful to add a link to an article explaining it with more details.
</pre>

feat: add prompt for starring repo

---

pages/courses/pyqs/index.tsx

<pre>
Because I didn't want to put up my WhatsApp number on FB.
</pre>

Add PYQs button - Course PYQs

---

middleware.ts

Added middleware to only allow bitsian to access the docs.

Email verfication

---

pages/api/auth/[...nextauth].tsx

<pre>
Auth now checks and blocks non student emails, across campuses
</pre>

Email Verification - v2

---

components/Menu.tsx

<pre>
Updated the Sitemap menu button for mobile view as well as desktop view (Clickable area for the svg to view Sitemap.) and the grid view for the Sitemap (centered).
</pre>
- [✓] Bug fix (non-breaking change which fixes an issue)
- [✓] I didnt push any `.env` files

Update the Sitemap button and grid view for sitemap

---

components/Menu.tsx

Reverts thenicekat/handoutsforyou#40

Revert "Update the Sitemap button and grid view for sitemap"

---

README.md

<pre>
Changed star history to be in dark mode.
</pre>

refactor: changed star history link README.md

---

pages/api/testimonials/add.ts
pages/ps/cutoffs/ps1/add.tsx
pages/ps/cutoffs/ps2/add.tsx
pages/testimonials/add.tsx

Reverts thenicekat/handoutsforyou#51
cc: @proinators @RCR0101

Revert "Remove testimonial handling"

---

LICENSE

feat: add GPL V3 LICENSE

---

pages/ps/cutoffs/ps1/index.tsx
pages/ps/cutoffs/ps2/index.tsx

added range filter in ps1 and ps2 cutoffs

feat: add upper and lower limit in ps pages

---

pages/ps/cutoffs/ps1/index.tsx
pages/ps/cutoffs/ps2/index.tsx

fix : ps2 cutoff ui issue 
